import { Inter, Jost, Montserrat, Outfit, Prompt, Roboto, Sora, Varela_Round } from "next/font/google";
import "./globals.css";


const inter = Montserrat({ subsets: ["vietnamese"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={`${inter.className} bg-slate-200 font-medium`}>
        {children}</body>
    </html>
  );
}
